#!/bin/bash -x




#Take a range from 0 – 100, find the digits that are repeated twice like 33, 77,etc and store them in an array


for((i=1;i<100;i++))
do
temp=$(($i))
rem1=$(($i%10))
temp=$(($temp/10))
rem2=$(($temp%10))


if [ $rem1 -eq $rem2 ]
then
     echo $i
fi
done
