#!/bin/bash -x

read -p "Enter the days number" day

case $day in
	1)
		echo "Monday";;
	2)
		echo "Tuesday";;
	3)
		echo "wednesday";;
	4)
		echo "Thursday";;
	5)
		echo "friday";;
	6)
		echo "saturday";;
	7)
		echo "sunday";;
	*)
		echo "Enter the correct value";;
esac
